//! JavaScript engine API used by Nexus Browser.

use std::fmt;

/// Result type used by the JavaScript subsystem.
pub type JsEngineResult<T> = Result<T, JsEngineError>;

/// JavaScript engine lifecycle state.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JsEngineState {
    Unloaded,
    Loaded,
    Starting,
    Running,
    Stopping,
    Failed,
}

/// JavaScript engine capabilities.
#[derive(Debug, Clone)]
pub struct JsEngineCapabilities {
    pub ecmascript: bool,
    pub wasm: bool,
    pub modules: bool,
    pub workers: bool,
    pub shared_array_buffer: bool,
    pub bigint: bool,
    pub jit: bool,
    pub sandboxing: bool,
    pub microvm: bool,
    pub hot_reload: bool,
}

impl Default for JsEngineCapabilities {
    fn default() -> Self {
        Self {
            ecmascript: true,
            wasm: true,
            modules: true,
            workers: true,
            shared_array_buffer: true,
            bigint: true,
            jit: true,
            sandboxing: true,
            microvm: true,
            hot_reload: true,
        }
    }
}

/// Configuration passed to a JavaScript engine.
#[derive(Debug, Clone)]
pub struct JsEngineConfiguration {
    pub name: String,
    pub version: String,
    pub executable: Option<String>,
    pub sandboxed: bool,
    pub microvm_enabled: bool,
    pub jit_enabled: bool,
    pub wasm_enabled: bool,
    pub max_memory_mb: Option<u64>,
    pub max_heap_mb: Option<u64>,
}

impl Default for JsEngineConfiguration {
    fn default() -> Self {
        Self {
            name: "unknown".to_string(),
            version: "0.0.0".to_string(),
            executable: None,
            sandboxed: true,
            microvm_enabled: true,
            jit_enabled: true,
            wasm_enabled: true,
            max_memory_mb: Some(512),
            max_heap_mb: Some(256),
        }
    }
}

/// Errors generated by the JavaScript subsystem.
#[derive(Debug)]
pub enum JsEngineError {
    AlreadyLoaded,
    NotLoaded,
    AlreadyRunning,
    NotRunning,
    InvalidState,
    LaunchFailed(String),
    InitializationFailed(String),
    ShutdownFailed(String),
    ExecutionFailed(String),
    EngineNotFound(String),
    EngineAlreadyRegistered(String),
    ConfigurationError(String),
    Unsupported(String),
}

impl fmt::Display for JsEngineError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::AlreadyLoaded => write!(f, "JavaScript engine is already loaded"),
            Self::NotLoaded => write!(f, "JavaScript engine is not loaded"),
            Self::AlreadyRunning => write!(f, "JavaScript engine is already running"),
            Self::NotRunning => write!(f, "JavaScript engine is not running"),
            Self::InvalidState => write!(f, "invalid JavaScript engine state"),
            Self::LaunchFailed(message) => write!(f, "JavaScript engine launch failed: {message}"),
            Self::InitializationFailed(message) => {
                write!(f, "JavaScript engine initialization failed: {message}")
            }
            Self::ShutdownFailed(message) => {
                write!(f, "JavaScript engine shutdown failed: {message}")
            }
            Self::ExecutionFailed(message) => {
                write!(f, "JavaScript execution failed: {message}")
            }
            Self::EngineNotFound(name) => {
                write!(f, "JavaScript engine not found: {name}")
            }
            Self::EngineAlreadyRegistered(name) => {
                write!(f, "JavaScript engine already registered: {name}")
            }
            Self::ConfigurationError(message) => {
                write!(f, "JavaScript engine configuration error: {message}")
            }
            Self::Unsupported(message) => write!(f, "unsupported operation: {message}"),
        }
    }
}

impl std::error::Error for JsEngineError {}

/// Common interface implemented by JavaScript engines.
pub trait JsEngine: Send {
    /// Returns the engine name.
    fn name(&self) -> &str;

    /// Returns the engine version.
    fn version(&self) -> &str;

    /// Returns the current engine state.
    fn state(&self) -> JsEngineState;

    /// Returns the engine capabilities.
    fn capabilities(&self) -> &JsEngineCapabilities;

    /// Returns the engine configuration.
    fn configuration(&self) -> &JsEngineConfiguration;

    /// Loads the engine.
    fn load(&mut self) -> JsEngineResult<()>;

    /// Starts the engine runtime.
    fn start(&mut self) -> JsEngineResult<()>;

    /// Stops the engine runtime.
    fn stop(&mut self) -> JsEngineResult<()>;

    /// Unloads the engine.
    fn unload(&mut self) -> JsEngineResult<()>;

    /// Executes JavaScript source.
    fn execute(&mut self, source: &str) -> JsEngineResult<String>;

    /// Returns whether the engine is healthy.
    fn is_healthy(&self) -> bool;
}
